export const ADD_TO_SERVER = "ADD_TO_SERVER"
export const ADD_TO_SERVER_SUCCESS = "ADD_TO_SERVER_SUCCESS"
export const ADD_TO_SERVER_REJECT = "ADD_TO_SERVER_REJECT"


export const GET_MESSAGES = "GET_MESSAGES"
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const GET_MESSAGES_REJECT = "GET_MESSAGES_REJECT"


export const SEND_OFFLINE_MESSAGES = "SEND_OFFLINE_MESSAGES"